### ISSUE TITLE
[Milestone Tracker] Implementation of manual CPFP for Revault Managers  

### ISSUE THREAD

**Issue by Zshan0** [revault/revaultd#411]
This issue is to update the community on the progress that will be made on the implementation of manual CPFP command for managers. The addition of a JSONRPC Command on `revaultd`’s side will be followed by the implementation of a button to do the same on `revault-gui`. The following list is for the tasks that are relevant to `revaultd` only. Please refer to my documentation [here](https://docs.google.com/document/d/1cYATCmwks22gp7fh3IEadhsxpz6sI5kwnSAg4dBnaMM/edit?usp=sharing) and feel free to drop feedbacks if necessary.
- [ ] Documenting a JSONRPC Command and its interaction with `revault-gui`
- [ ] Finalizing a design for the API
- [ ] Implementation of the API in `revaultd`
- [ ] Completion of tests for the API
- [ ] Finish the tasks related on `revault-gui`
- [ ] Final merge testing
